<?php
	$logo = '';
	$bg_open = '2';
	$bgimg = '';
	$arr_navico = 'a:4:{i:1;s:10:"fa fa-home";i:2;s:12:"fa fa-twitch";i:3;s:0:"";i:4;s:0:"";}';
	$arr_sortico = 'N;';
	$index_width = '1170';
	$index_num = '4';
	$fous_open = '1';
	$fous_id = '1';
	$dy_id = '9';
	$cms_id = '1,6,9,10';
	$side_qq = '1501700017';
	$compress_html = '1';
	$more = '1';
	$more_html = '<li><a href="https://pjax.cn/album.html"><i class="fa fa-picture-o"></i> 相册</a></li><li><a href="https://pjax.cn/?plugin=gs_player"><i class="fa fa-music"></i> 音乐</a></li><li><a href="https://pjax.cn/archivers.html"><i class="fa fa-list"></i> 归档</a></li><li><a href="https://pjax.cn/links.html"><i class="fa fa-link"></i> 链接</a></li>';
	$Slide = '1';
	$Slide1 = 'https://pjax.cn/content/templates/FLY/img/blue.jpg';
	$Surl1 = 'https://pjax.cn';
	$Slide2 = 'http://pjax.cn/content/templates/FLY/img/red.jpg';
	$Surl2 = 'https://pjax.cn';
	$Slide3 = 'https://pjax.cn/content/templates/FLY/img/blue.jpg';
	$Surl3 = 'https://pjax.cn';
	$Sorts = '1';
	$Sorth1 = '相册图库';
	$Sortp1 = '相册图库介绍';
	$Sorta1 = 'https://pjax.cn/album.html';
	$Sorth2 = '音乐页面';
	$Sortp2 = '音乐点播页面';
	$Sorta2 = 'https://pjax.cn/?plugin=gs_player';
	$Sorth3 = '文章归档';
	$Sortp3 = '瞎J8乱写了';
	$Sorta3 = 'https://pjax.cn/archivers.html';
	$Sorth4 = '微言碎语';
	$Sortp4 = '微言碎语1231';
	$Sorta4 = 'https://pjax.cn/t';
	$Sorth5 = '留言互动';
	$Sortp5 = '不要打广告哦~';
	$Sorta5 = 'https://pjax.cn/contact.html';
	$Sorth6 = '友情链接';
	$Sortp6 = '友情链接自助申请';
	$Sorta6 = 'https://pjax.cn/links.html';
	$ads = '1';
	$adimg1 = 'https://pjax.cn/content/templates/FLY/img/ad.png';
	$adurl1 = 'https://pjax.cn/';
	$adimg2 = 'https://pjax.cn/content/templates/FLY/img/ad.png';
	$adurl2 = 'https://pjax.cn/';
?>